version: '3.8'
services:
  next-app:
    build:
      context: .
      dockerfile: ./my-next-app/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./my-next-app:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true